force-app/main/default/objects/Contact/fields/Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment_Date__c</fullName>
    <label>Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Used to store payments per project.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Payment {0}</displayFormat>
        <label>Payment  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Please enter payment amount.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <inlineHelpText>Please enter date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Used to track the status of payment.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object to store projects, view total amount spent on project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment_Date__c</fullName>
    <label>Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount of Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
public class TestFactory {
    public static List<Contact> contactCreation(Integer count){
      list<Contact> contacList = new list<Contact>();
        if(count!=null){
            for(Integer i= 0; i<count; i++){
                Contact contactObj = new Contact();
                contactObj.FirstName = 'My Contact '+count;
                contactObj.LastName = 'Surname';
                contacList.add(contactObj);
            }
        }else{
            Contact contactObj = new Contact();
                contactObj.FirstName = 'My Contact '+count;
                contactObj.LastName = 'Surname';
                contacList.add(contactObj);
        }
        return contacList;
    }
    
    public static List<Project__c> projectCreation(Integer count){
      list<Project__c> projectList = new list<Project__c>();
        if(count!=null){
            for(Integer i= 0; i<count; i++){
                Project__c projectObj = new Project__c();
                projectObj.Name = 'My Project__c '+count;
                projectObj.Most_Recent_Payment_Date__c = System.today();
                projectObj.Total_Amount__c = 100;
                projectList.add(projectObj);
            }
        }else{
            Project__c projectObj = new Project__c();
                projectObj.Name = 'My Project__c '+count;
                projectObj.Most_Recent_Payment_Date__c = System.today();
                projectObj.Total_Amount__c = 100;
                projectList.add(projectObj);
        }
        return projectList;
    }
    
    public static List<Payment__c> paymentCreation(Integer count){
      list<Payment__c> paymentList = new list<Payment__c>();
        if(count!=null){
            for(Integer i= 0; i<count; i++){
                Payment__c paymentObj = new Payment__c();
                paymentObj.Payment_Date__c = System.today();
                 paymentObj.Payment_Amount__c = 100;
                 paymentObj.Payment_Status__c = 'Billed';
                paymentList.add(paymentObj);
            }
        }else{
             Payment__c paymentObj = new Payment__c();
                paymentObj.Payment_Date__c = System.today();
                 paymentObj.Payment_Amount__c = 100;
                 paymentObj.Payment_Status__c = 'Billed';
                paymentList.add(paymentObj);
        }
        return paymentList;
    }
}