force-app/main/default/objects/Contact/fields/Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment_Date__c</fullName>
    <label>Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Amount_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Payments__c</fullName>
    <label>Total Amount of Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Used to store payments per project.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Payment {0}</displayFormat>
        <label>Payment  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Method_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Payment__c</fullName>
    <label>Method of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Please enter payment amount.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <inlineHelpText>Please enter date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Used to track the status of payment.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object to store projects, view total amount spent on project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment_Date__c</fullName>
    <label>Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentDetailsController.cls
public class PaymentDetailsController {
    @AuraEnabled
    public static List<Contact> getContactDetails() {
        return [SELECT Id, Total_Amount_of_Payments__c, FirstName, LastName, Most_Recent_Payment_Date__c FROM Contact WHERE Total_Amount_of_Payments__c != null];
    }
 	
    @AuraEnabled
    public static List<Payment__c> getPaymentList(String contactId) {
        return [SELECT Id, Name,Project__r.Name,Payment_Amount__c, Payment_Date__c, Payment_Status__c, Person__c,Method_of_Payment__c FROM Payment__c WHERE Person__c =:contactId];
    }
    /*
    @AuraEnabled
    public static string dmlOnContacts(Object data, String removeContactIds) {
        List<Contact> updateContact = (List<Contact>) JSON.deserialize(JSON.serialize(data), List<Contact>.class);
        List<Contact> deleteContact = new List<Contact>();
 
        if(String.isNotBlank(removeContactIds)){
            List<Id> contactIds = removeContactIds.split(',');
            deleteContact = [SELECT Id FROM Contact WHERE Id IN :contactIds];
        }
 
        try {
            if(updateContact != null && !updateContact.isEmpty()){
              //  upsert updateContact;
            }
 
            if(deleteContact != null && !deleteContact.isEmpty()){    
             //   delete deleteContact;
            }
            return 'Success: Contact(s) upsert/delete successfully';
        }
        catch (Exception e) {
            String errorMsg = 'The following exception has occurred: ' + e.getMessage();
            throw new AuraHandledException(ErrorMsg);
        }
       // return '';
    } */
    
    @AuraEnabled
    public static string submitContact(Object contactList) {
        List<Contact> updateContact = (List<Contact>) JSON.deserialize(JSON.serialize(contactList), List<Contact>.class);
        List<Contact> deleteContact = new List<Contact>();
 
            if(updateContact != null && !updateContact.isEmpty()){
                Database.update(updateContact,false);
            }
 
            return 'Success: Contact(s) updated successfully';
        
      
       // return '';
    }
    
    @AuraEnabled
    public static string deletePayment(String paymentId) {
 
            System.debug('paymentId : '+paymentId);
            if(String.isNotBlank(paymentId)){
                Delete [Select Id FROM Payment__c WHERE Id=:paymentId];
                return 'Success';
            }
       return null;
    }
    
    @AuraEnabled
    public static string submitPayment(Object paymentList) {
        List<Payment__c> updatePayment = (List<Payment__c>) JSON.deserialize(JSON.serialize(paymentList), List<Payment__c>.class);
            if(updatePayment != null && !updatePayment.isEmpty()){
                Database.update(updatePayment,false); 
            }

            return 'Success: Payment(s) update successfully';
       
       
       // return '';
    }
}