force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Used to store payments per project.</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Payment {0}</displayFormat>
        <label>Payment  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Method_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Payment__c</fullName>
    <label>Method of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Please enter payment amount.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <inlineHelpText>Please enter date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Used to track the status of payment.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object to store projects, view total amount spent on project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentDetailsControllerTest.cls
@isTest
public class PaymentDetailsControllerTest {
 @testSetup static void setup() {
       List<Contact> contList= TestFactory.contactCreation(1);
        insert contList;
     
        List<Project__c> projectList= TestFactory.projectCreation(1);
     projectList[0].Person__c =contList[0].id;
        insert projectList;
     
     	List<Payment__c> paymentList= TestFactory.paymentCreation(1);
     paymentList[0].Person__c =contList[0].id;
         paymentList[0].Project__c=projectList[0].id;
        insert paymentList;
    }
    
    @isTest static void testWarmTemp() {
         List<Contact> pifList = [Select Id FROM Contact];
        PaymentDetailsController.getContactDetails();
    }
    
    @isTest static void testGetPaymentListp() {
        List<Contact> contList = [Select Id FROM Contact limit 1];
         List<Payment__c> pifList = [Select Id,Name,Project__r.Name,Payment_Amount__c, Payment_Date__c, Payment_Status__c, Person__c,Method_of_Payment__c FROM Payment__c];
        PaymentDetailsController.getPaymentList(contList[0].Id);
    }
    
    @isTest static void testsubmitContact() {
        List<Contact> contList = [Select Id FROM Contact limit 1];
         List<Payment__c> pifList = [Select Id,Name,Project__r.Name,Payment_Amount__c, Payment_Date__c, Payment_Status__c, Person__c,Method_of_Payment__c FROM Payment__c];
        PaymentDetailsController.submitContact(contList);
    }
    
     @isTest static void testdeletePayment() {
        List<Contact> contList = [Select Id FROM Contact limit 1];
         List<Payment__c> pifList = [Select Id,Name,Project__r.Name,Payment_Amount__c, Payment_Date__c, Payment_Status__c, Person__c,Method_of_Payment__c FROM Payment__c];
        PaymentDetailsController.deletePayment(pifList[0].Id);
    }
    
     @isTest static void testsubmitPayment() {
        List<Contact> contList = [Select Id FROM Contact limit 1];
         List<Payment__c> pifList = [Select Id,Name,Project__r.Name,Payment_Amount__c, Payment_Date__c, Payment_Status__c, Person__c,Method_of_Payment__c FROM Payment__c];
        PaymentDetailsController.submitPayment(pifList);
    }
}